# Yuanheng
# create: Jul 23, 2020
# 1. change how to use spike-in
# 2. add lysis buffer info

```{r setup}
#setwd("/media/yuanheng/SD-64g2/files/Projects/Oregon/R-git")
	
lapply(c("ggplot2", "gridExtra",'vegan', 'labdsv', 'tidyverse', 'scatterplot3d', 'gridBase','conflicted', 'grid', 'ggcorrplot','here'), library, character.only=T)
	
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("importance", "sjSDM")
	
dr_here()
	
```

```{r load files}
# formatted data
otu.env1.present = read.csv(here('kelpie','formatted_data','present2_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
dim(otu.env1.present)
	
# ('HJA_analyses_Kelpie/Kelpie_maps' folder) 
otu.env1.noS2 = read.csv(here('..','..','Kelpie_maps', 'outputs_minimap2_20200221_F2308_f0x2_q48_kelpie20200214_vsearch97','sample_by_species_table_F2308_minimap2_20200221_kelpie20200723.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
dim(otu.env1.noS2) 
names(otu.env1.noS2)[1:27]
	
names(otu.env1.noS2)[1:26]=c('SiteName', 'UTM_E','UTM_N','old.growth.str', 'yrs.disturb','point.ID','poly.ID','AGENCY','unit.log', 'name.log','log.yr','yrs.log.2018','log.treat','yrs.disturb.level', 'elevation','canopy.ht','min.T','max.T', 'precipitation','metre.road', 'metre.stream', 'yrs.disturb.min','hja','trap','session','site_trap_period')
	
a1 = dplyr::select(otu.env1.noS2, contains('spike'))
str(a1)
spike_input = c('COI_SPIKE_Coleoptera_Mordellidae_0.4'=1, 'COI_SPIKE_Coleoptera_Elateridae_0.8'=9)
	
# lysis buffer info
lysis = read.csv(here('kelpie', 'lysis_buffer_volume_20200724.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
# 'lysis_buffer_volume_20200715.csv' has error
str(lysis)
	

```

```{r explore lysis-info}
str(lysis)
head(lysis)
	
table(lysis$aliquot)
	
par(mfrow=c(1,2))
hist(lysis$added.lysis.buffer.ml.[lysis$aliquot==1.2])
hist(lysis$added.lysis.buffer.ml.[lysis$aliquot==0.6])
# add aliquot==1.2 when the DNA concentration is too low
	
table(lysis$lysis.batch)
	
```

```{r format lysis-info}
str(lysis)
sort(unique(lysis$sample)) == sort(unique(otu.env1.noS2$site_trap_period))
	
names(otu.env1.noS2)[1:26]
table(is.na(otu.env1.noS2$site_trap_period))
	
# change '_' to '-'
a = str_replace(lysis$sample, "HOBO_", 'HOBO-')
a = str_replace(a, "SM_", 'SM-')
data.frame(a, lysis$sample)
lysis$sample = a
	
dim(otu.env1.noS2)
	
otu.env1 = dplyr::left_join(otu.env1.noS2, lysis, by=c('site_trap_period'='sample'))
dim(otu.env1)
	
table(is.na(otu.env1$'added.lysis.buffer.ml.'))
	
# check which samples are not matched
for (i in 1:length(otu.env1$site_trap_period)) {
	if (match(otu.env1$site_trap_period[i], lysis$sample, nomatch=0)==0) {
		print(otu.env1$site_trap_period[i])
	}
}
	
[1] "HOBO-063_M1_S2"
[1] "SM-06_M1_S1"
[1] NA
[1] NA
	
otu.env1 = subset(otu.env1, site_trap_period!='NA')
otu.env1 = subset(otu.env1, site_trap_period!="HOBO-063_M1_S2" & site_trap_period!="SM-06_M1_S1")
	
otu.env1 = otu.env1[,c(1:26, 1176:1180, 27:1175)]
names(otu.env1)[1:32]
	
# .. calculate FSL
spike_reads = data.frame(
					select(otu.env1, 'site_trap_period'),
					select(otu.env1, names(spike_input)[1])/spike_input[1],
					select(otu.env1, names(spike_input)[2])/spike_input[2] )
	
spike = data.frame(select(spike_reads, 'site_trap_period'), spike.mean=rowMeans(spike_reads[,2:3]))
rowMeans(spike_reads[235,2:3])
dim(spike)
	
otu.env1$lysis.ratio = otu.env1$aliquot/otu.env1$'added.lysis.buffer.ml.'
hist(otu.env1$lysis.ratio)
	
dim(otu.env1)
	
otu.env1 = dplyr::left_join(otu.env1, spike, by=c('site_trap_period'='site_trap_period'))
otu.env1 = otu.env1[,c(1:31, 1181:1182, 32:1180)]
str(otu.env1[,1:34])
	
# 1182-33-2(spike) = 1147
#FSL[i,j] = log(otu.env1$mapped_reads/(lysis*spike))
FSL = select(otu.env1, 'site_trap_period', 'lysis.ratio','spike.mean', starts_with('R'))
dim(FSL)
	
a = FSL[,-c(1:3)]/(FSL$lysis.ratio*FSL$spike.mean)
dim(a)
	
a[1,5] == FSL[1,8]/(FSL$lysis.ratio[1]*FSL$spike.mean[1])
a[11,50] == FSL[11,53]/(FSL$lysis.ratio[11]*FSL$spike.mean[11])
	
FSL = cbind(FSL[,1:3],a)
sum(as.matrix(FSL[,4:1150]) )
str(FSL[,1:5])
	
par(mfrow=c(1,2))
hist(as.vector(as.matrix(FSL[,4:1150])),breaks=100)
hist(as.vector(as.matrix(log(FSL[,4:1150]))),breaks=100)
# not necessary to log now as sjSDM is a probit model
	
# ... combine with envir factors
names(otu.env1)[1:34]
print(c(dim(otu.env1), dim(FSL)))
	
fsl.env = dplyr::left_join(data.frame(otu.env1[,1:33]), data.frame(FSL[,c(1,4:1150)]), by=c('site_trap_period'='site_trap_period'))
dim(fsl.env)
sort(fsl.env$site_trap_period) == sort(otu.env1$site_trap_period)
	
write.table(fsl.env, here('kelpie','formatted_data','FSL_sample_by_species_table_F2308_minimap2_20200221_kelpie20200723.csv'), row.names=F, sep=',')
	
```

```{r re-format OTU table}
print(c(dim(otu.env1.present), dim(fsl.env)))
# 237 1197  235 1180
	
data.frame(names(otu.env1.present)[1:50], c(names(fsl.env)[1:33],rep(NA,17)))
#names(fsl.env)[c(1:26, 32:33)]
data.frame(a=sort(otu.env1.present$site_trap_period), b=c(sort(fsl.env$site_trap_period),NA,NA) )
	
fsl.env1 = dplyr::inner_join(otu.env1.present[,c(1:50)], fsl.env[,c(26,32:33)], by=c('site_trap_period', 'site_trap_period'), copy=F) 
dim(fsl.env1)
	
names(fsl.env)[34:1180] == names(otu.env1.present)[51:1197]
	
fsl.env1 = cbind(fsl.env1, fsl.env[,34:1180])
	
str(fsl.env1[,1:53])
	
write.table(fsl.env1, here('kelpie','formatted_data','FSL2_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200723.csv'), row.names=F, sep=',')
	

```

```{r subsets}
#otu.env1.present, fsl.env1
# ......................... subsets of data ..................................
dataI.1.present = subset(otu.env1.present, session == 'S1' & trap == 'M1' )
	
dataII.1.present = subset(otu.env1.present, session == 'S2' & trap == 'M1' )
	
dataI.1.fsl = subset(fsl.env1, session == 'S1' & trap == 'M1' )
	
dataII.1.fsl = subset(fsl.env1, session == 'S2' & trap == 'M1' )
	
print(c(dim(dataI.1.fsl), dim(dataI.1.present)))
	
print(c(dim(dataII.1.fsl), dim(dataII.1.present)))
	
# .... if there's all zero OTUs ....
# .... S1
b = data.frame(otu=colnames(select(dataI.1.fsl, contains('__'))), zero=apply(select(dataI.1.fsl, contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
table(b$zero)
	
dataI.1.fsl2 = dplyr::select(dataI.1.fsl, -contains('__'),b$otu[b$zero==F])
dim(dataI.1.fsl2)
dataI.1.fsl2[1:5,53:60]
	
b = data.frame(otu=colnames(select(dataI.1.present,contains('__'))), zero=apply(select(dataI.1.present,contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
dim(b)
	
dataI.1.present2 = dplyr::select(dataI.1.present, -contains('__'),b$otu[b$zero==F])
dim(dataI.1.present2)
dataI.1.present2[1:5,34:40]
	
print(c(dim(dataI.1.fsl2), dim(dataI.1.present2)))
	
dataI.1.fsl2$site_trap_period[41:42]
dataI.1.present2$site_trap_period[41:43] 
dataI.1.present2$site_trap_period[43:88] == dataI.1.fsl2$site_trap_period[42:87]
# "SM-06_M1_S1" (42) -> no info for lysis!
#
# ... session II
b = data.frame(otu=colnames(select(dataII.1.present,contains('__'))), zero=apply(select(dataII.1.present,contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
table(b$zero)
	
dataII.1.present2 = dplyr::select(dataII.1.present, -contains('__'),b$otu[b$zero==F])
dim(dataII.1.present2)
dataII.1.present2[1:5,34:40]
	

b = data.frame(otu=colnames(select(dataII.1.fsl,contains('__'))), zero=apply(select(dataII.1.fsl,contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
table(b$zero)
	
dataII.1.fsl2 = dplyr::select(dataII.1.fsl, -contains('__'),b$otu[b$zero==F])
dim(dataII.1.fsl2)
dataII.1.fsl2[1:5,34:40]
	
print(c(dim(dataII.1.fsl2), dim(dataII.1.present2)))
	
# . write table
write.table(dataI.1.fsl2, here('kelpie','formatted_data', 'session_trap', 's1m1_relAbun2_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'))
	
```
