---
title: "neighbors"
author: "Douglas Yu"
date: "15/09/2020"
output: html_document
---

```{r setup, eval=TRUE, include=TRUE}
# copy the following into each script   
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)

# script-specific libraries
suppressPackageStartupMessages({
  library(stringdist)
  library(vegan)
})

# general-use packages
suppressPackageStartupMessages({
  library(here)
  library(fs)
  library(glue)
  library(tidyverse) # loads a bunch of packages (see below)
  library(readxl)
  library(cowplot)
  library(lubridate)
  library(patchwork)
  library(broom)
  library(ggeffects)
  library(viridis)
  library(arsenal) # for summary(comparedf())
  library(sjmisc) # for rotate_df()
  library(envDocument)
  library(inspectdf)
  library(conflicted)
})

tidyverse_packages(include_self = TRUE) # this lists the tidyverse packages that are loaded by just running the single command `library(tidyverse)
#  [1] "broom"      "cli"        "crayon"     "dbplyr"     "dplyr"      "forcats"    "ggplot2"    "haven"     
#  [9] "hms"        "httr"       "jsonlite"   "lubridate"  "magrittr"   "modelr"     "pillar"     "purrr"     
# [17] "readr"      "readxl"     "reprex"     "rlang"      "rstudioapi" "rvest"      "stringr"    "tibble"    
# [25] "tidyr"      "xml2"       "tidyverse" 

# Sometimes, two or more packages use the same function names. the {conflicted} package lets you set which package gets precedence. For example, the next line enforces that filter() refers to the {dplyr} package. If you want to use the command filter() from a different package, you just need to precede it with the desired package name, like this: stats::filter.  
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("mutate", "dplyr", quiet = TRUE)
conflict_prefer("select", "dplyr", quiet = TRUE)
conflict_prefer("summarise", "dplyr", quiet = TRUE)
conflict_prefer("first", "dplyr", quiet = TRUE)
conflict_prefer("here", "here", quiet = TRUE)
conflict_prefer("separate", "tidyr", quiet = TRUE)
conflict_prefer("unite", "tidyr", quiet = TRUE)
conflict_prefer("intersect", "dplyr", quiet = TRUE)
conflict_prefer("setdiff", "dplyr", quiet = TRUE) # w/out this, R crashes
conflict_prefer("to_factor", "sjmisc", quiet = TRUE)
conflict_prefer("trim", "glue", quiet = TRUE)

# Provide real numbers, not scientific notation.
options(scipen = 999)
```



```{r}
neighbors <- read_csv("Dropbox/Working_docs/Luo_Mingjie_Oregon/HJA_analyses_Kelpie/HJA_scripts/08_reference_sequences_datasets/neighbors_20191204.txt") %>% select(-index, -Distance) %>% 
    mutate(SiteName = str_replace(SiteName, "HOBO-", "HOBO")) 

nwide <- neighbors %>% select(SiteName) %>% distinct()
nwide2 <- as.vector(neighbors$NeighborName)
nwide2 <- matrix(nwide2, nrow = 96, ncol = 5, byrow = TRUE)
colnames(nwide2) <- c("neighbor1", "neighbor2", "neighbor3", "neighbor4", "neighbor5")
nwide2 <- as_tibble(nwide2)
nwide <- bind_cols(nwide, nwide2)

write_csv(nwide, "Dropbox/Working_docs/Luo_Mingjie_Oregon/HJA_analyses_Kelpie/HJA_scripts/08_reference_sequences_datasets/neighbors_20191204_wide.csv")
```

