---
title: "ecocopula"
author: "Douglas Yu"
date: "03/12/2020"
output: html_document
---

```{r setup, eval=TRUE, include=TRUE}
# copy the following into each script   
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)

# script-specific libraries
suppressPackageStartupMessages({
  library(stringdist)
  library(vegan)
  library(mvabund)
  library(ordinal)
  library(ecoCopula)
  library(corrplot)
  library(ggrepel)
  library(RColorBrewer)
  library(tidygraph)
  library(ggraph)
})

# general-use packages
suppressPackageStartupMessages({
  library(here)
  library(fs)
  library(glue)
  library(tidyverse)
  library(readxl)
  library(cowplot)
  library(lubridate)
  library(patchwork)
  library(broom)
  library(ggeffects)
  library(viridis)
  library(arsenal) # for summary(comparedf())
  library(sjmisc) # for rotate_df()
  library(envDocument)
  library(inspectdf)
  library(conflicted)
})

# Provide real numbers, not scientific notation.
options(scipen = 999)
```

```{r read data}
otuenv <- readRDS(here("data", "otuenv.RDS"))

env <- otuenv$env

otuqp <- otuenv$otu # qp data

otupa <- otuqp
otupa[otupa > 0] <- 1 # pa data
```

manyglm PA
```{r manyglm pa}
abund <- "pa"
glue("otu{abund}")

otu.ord <- mvabund(get(glue("otu{abund}")))
is.mvabund(otu.ord)

# otu.mod0 <- manyglm(otu.ord ~ 1, family = "binomial")
# 
# plot(otu.mod0) # chk residuals
# 
# otu.mod0.ord <- cord(otu.mod0)
# # plot(otu.mod0.ord, biplot = TRUE)

# with elevation covariate
otu.mod1 <- manyglm(otu.ord ~ elevation_m, family = "binomial", data = env)

plot(otu.mod1) # chk residuals

otu.mod1.ord <- cord(otu.mod1)
```

```{r extract factors}
ord_to_plot <- otu.mod1.ord # otu.mod0.ord

site_res <- data.frame(ord_to_plot$scores, env)

sp_res <- data.frame(ord_to_plot$loadings)
```

```{r plot ecoCopula ordination}
alpha <- 4
p0 <- ggplot() + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Factor1 * alpha * 0.95, 
                   yend = Factor2 * alpha * 0.95), 
               data = sp_res, 
               size = .1) +
  geom_point(aes(x = Factor1, y = Factor2, 
                 color = elevation_m, 
                 size = YrsSinceDist, 
                 shape = as.factor(insideHJA)
                 ), 
             data = site_res) + 
  scale_color_gradientn(colours = brewer.pal(n = 10, name = "RdYlBu")) +
  theme_classic() + 
  labs(title = glue("HJA, ecoCopula ordination, {abund}"))

p0
```

Manyany QP ordinal
```{r Manyany qp}
abund <- "qp"
otu.ord <- get(glue("otu{abund}")) %>% 
  mutate(across(everything(), factor))

source(here("1.1_Manyany.R"))

# with elevation covariate
otu.mod1 <- Manyany("clm", otu.ord, abund ~ elevation_m, data = env)

plot(otu.mod1) # chk residuals

otu.mod1.ord <- cord(otu.mod1)
```

```{r extract factors}
ord_to_plot <- otu.mod1.ord # otu.mod0.ord

site_res <- data.frame(ord_to_plot$scores, env)

sp_res <- data.frame(ord_to_plot$loadings)
```

```{r plot ecoCopula ordination}
alpha <- 4
p0 <- ggplot() + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Factor1 * alpha * 0.95, 
                   yend = Factor2 * alpha * 0.95), 
               data = sp_res, 
               size = .1) +
  geom_point(aes(x = Factor1, y = Factor2, 
                 color = elevation_m, 
                 size = YrsSinceDist, 
                 shape = as.factor(insideHJA)
                 ), 
             data = site_res) + 
  scale_color_gradientn(colours = brewer.pal(n = 10, name = "RdYlBu")) +
  theme_classic() + 
  labs(title = glue("HJA, ecoCopula ordination, {abund}"))

p0
```



Questions start here

1. offset(log(spikeins))
2. mvabund requires integers
4. Or should i use stackedsdm?  needs manual coding


offset(log(spikein))

manyglm QP 
```{r manyglm qp}
abund <- "qp"
otu.ord <- mvabund(get(glue("otu{abund}")))
is.mvabund(otu.ord)

# with elevation
otu.mod1 <- manyglm(otu.ord ~ elevation_m, 
                    family = "gamma",
                    composition = TRUE, # very slow
                    data = env
                    )
# offset(log(spikeins))
plot(otu.mod1) # chk residuals, not nice

otu.mod1.ord <- cord(otu.mod1)
```

Process output of cord()
```{r extract factors}
ord_to_plot <- otu.mod1.ord # otu.mod0.ord

site_res <- data.frame(ord_to_plot$scores, env)

sp_res <- data.frame(ord_to_plot$loadings)
```

```{r plot ecoCopula ordination}
alpha <- 4
p0 <- ggplot() + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Factor1 * alpha * 0.95, 
                   yend = Factor2 * alpha * 0.95), 
               data = sp_res, 
               size = .1) +
  geom_point(aes(x = Factor1, y = Factor2, 
                 color = elevation_m, 
                 size = YrsSinceDist, 
                 shape = as.factor(insideHJA)
                 ), 
             data = site_res) + 
  scale_color_gradientn(colours = brewer.pal(n = 10, name = "RdYlBu")) +
  theme_classic() + 
  labs(title = glue("HJA, ecoCopula ordination, {abund}"))

p0
```


stackedsdm QP
```{r ordinal and binomial stackedsdm qp}
# binomial
abund <- "pa"
otu.ord <- get(glue("otu{abund}"))
otu.mod1 <- stackedsdm(otu.ord, 
                       formula_X = ~ elevation_m, 
                       data = env,
                       family="binomial", 
                       do_parallel = TRUE, 
                       ncores = 4
                       )
plot(otu.mod1) # chk residuals
otu.mod1.ord <- cord(otu.mod1)

# ordinal
abund <- "qp"
otu.ord <- (get(glue("otu{abund}"))) %>%
    mutate(across(everything(), ~rank(.x, ties.method = "min")))
otu.mod1 <- stackedsdm(otu.ord, 
                       formula_X = ~ elevation_m, 
                       data = env,
                       family="ordinal", 
                       do_parallel = TRUE, 
                       ncores = 4
                       )
plot(otu.mod1) # chk residuals
otu.mod1.ord <- cord(otu.mod1)
```

```{r extract factors}
ord_to_plot <- otu.mod1.ord # otu.mod0.ord

site_res <- data.frame(ord_to_plot$scores, env)

sp_res <- data.frame(ord_to_plot$loadings)
```

```{r plot ecoCopula ordination}
alpha <- 4
p0 <- ggplot() + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Factor1 * alpha * 0.95, 
                   yend = Factor2 * alpha * 0.95), 
               data = sp_res, 
               size = .1) +
  geom_point(aes(x = Factor1, y = Factor2, 
                 color = elevation_m, 
                 size = YrsSinceDist, 
                 shape = as.factor(insideHJA)
                 ), 
             data = site_res) + 
  scale_color_gradientn(colours = brewer.pal(n = 10, name = "RdYlBu")) +
  theme_classic() + 
  labs(title = glue("HJA, ecoCopula ordination, {abund}"))

p0
```

