# Yuanheng
# create: May 25, 2020
# last modified: Aug 31, 2020
# apply NMDS for different sessions & mark them on geographic map

# apply NMDS on lidar_data ('10_eo_data')

```{r set-up}
#setwd('/media/yuanheng/SD-64g2/Downloads/backup2/HJA_analyses_Kelpie/sjSDM/R-git')
	
lapply(c("ggplot2", "gridExtra",'vegan', 'labdsv','tidyverse','scatterplot3d', 'gridBase','grid', 'here'),library,character.only=T)
	
dr_here()
packageVersion('vegan')
#[1] ‘2.5.6’ metaMDS
	
```

```{r read-in data}
otu.env1.spike.present2 = read.table(here('data','kelpie_data','formatted_data','old','present_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), sep=',', header=T, na.strings='NA')
	
otu.env1.spike.relAbun2 = read.table(here('data','kelpie_data','formatted_data','old','relAbun_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), sep=',', header=T, na.strings='NA')
	
# can skip if directly goes to 'subsets of data'
# 0/1 OTU
otu.env1.spike.present = read.csv(here('data','kelpie_data','formatted_data','old','present2_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
str(otu.env1.spike.present[,1:26])
	
# relAbun OTU
otu.env1.spike.relAbun = read.csv(here('data','kelpie_data','formatted_data','old','relAbun2_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
str(otu.env1.spike.relAbun[,1:26])
	
# lidar data
lidar.env = read.csv(here('..','..','HJA_scripts','10_eo_data','biodiversity_site_info_lidar_20200518_cleaned.txt'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
str(lidar.env)
	
```

```{r visualize lidar indices}
# pdf(here('results','descriptive-graph','describe_lidar_indices.pdf'), height=4, width=9)
par(mfrow=c(1,2))
	
plot(x = 1:dim(lidar.env)[1], y = lidar.env$l_p95, type='l', ylim=c(0, max(lidar.env[,c(4:8,10:14)])), main='black: p95, red: p25, blue: rumple')
lines(1:dim(lidar.env)[1], lidar.env$l_p95_all)
	
lines(1:dim(lidar.env)[1], lidar.env$l_p25_all, col='red')
lines(1:dim(lidar.env)[1], lidar.env$l_p25, col='red')
	
lines(1:dim(lidar.env)[1], lidar.env$l_rumple, col='blue')
	
plot(1:dim(lidar.env)[1], lidar.env$l_Cover_2m_4m, ylim=c(0,max(lidar.env[,4:7])*1.1), col='red', type='l', main='red: 2m_4m, blue: 2m, black: 4m_16m')
lines(1:dim(lidar.env)[1], lidar.env$l_Cover_2m_4m_all, col='red')
	
lines(1:dim(lidar.env)[1], lidar.env$l_Cover_2m_max, col='blue')
lines(1:dim(lidar.env)[1], lidar.env$l_Cover_2m_max_all, col='blue')
	
lines(1:dim(lidar.env)[1], lidar.env$l_Cover_4m_16m, col='black')
	
# dev.off()
	
```


```{r play-with-data}
# !!! 3 NAs in '4m_16m_all', but not any other cols ???
# can skip
# ... compare sitename of two datasets
# lidar & otu
print(c(dim(otu.env1.spike.present), dim(lidar.env)))
print(c(dim(otu.env1.spike.relAbun), dim(lidar.env)))
# 237, 96 cols
	
sort(unique(otu.env1.spike.present$SiteName)) == sort(unique(lidar.env$SiteName))
sort(unique(otu.env1.spike.relAbun$SiteName)) == sort(unique(lidar.env$SiteName))
# 94 vs 96
	
# test 'SiteName' in lidar & otu 
lidar1= lidar.env[,1:3]
otu1 = otu.env1.spike.present[,1:3]
otu2 = otu.env1.spike.relAbun[,1:3]
	
otu1.lidar=dplyr::inner_join(otu1, lidar1, by=c('SiteName', 'SiteName'), copy=F)
otu2.lidar=dplyr::inner_join(otu2, lidar1, by=c('SiteName', 'SiteName'), copy=F)
unique(otu1.lidar$SiteName) == unique(otu2.lidar$SiteName)
	
otu1.lidar$UTM_E.x == otu2.lidar$UTM_E.y
	
# 94 sites are selected
rm(lidar1, otu1, otu2, otu1.lidar, otu2.lidar)
	
# check lidar variables
summary(as.data.frame(select(lidar.env, starts_with('l_'))))
# !!! 3 NAs in '4m_16m_all', but not any other cols ???
	
```

```{r make-table}
# can skip
# ..... align lidar with otu
# . 0/1 OTU
otu = otu.env1.spike.present
	
# . relAbun OTU
otu = otu.env1.spike.relAbun
	
dim(otu)
otu2 = dplyr::left_join(otu, select(lidar.env,-contains('UTM_')), by=c('SiteName', 'SiteName'), copy=F)
dim(otu2)
	
names(otu2[,1186:1197])
otu2 = otu2[ , c(1:39, 1187:1197, 40:1186)]
names(otu2[,20:51])
names(otu2[,1190:1197])
	
# write.table(otu2, file=here('data','kelpie_data','formatted_data','old', 'present_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), sep=',',row.names=F)
	
# write.table(otu2, file=here('data','kelpie_data','formatted_data','old', 'relAbun_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), sep=',',row.names=F)
	
otu.env1.spike.relAbun2 = otu2
	
otu.env1.spike.present2 = otu2
rm(otu, otu2)
	
```

```{r subsets of data}
# 0/1
dataI.1.spike.present = subset(otu.env1.spike.present2, session == 'S1' & trap == 'M1' )
dataI.2.spike.present = subset(otu.env1.spike.present2, session == 'S1' & trap == 'M2' )
	
dataII.1.spike.present = subset(otu.env1.spike.present2, session == 'S2' & trap == 'M1' )
dataII.2.spike.present = subset(otu.env1.spike.present2, session == 'S2' & trap == 'M2' )
	
print(c(dim(dataI.1.spike.present),dim(dataI.2.spike.present), dim(dataII.1.spike.present), dim(dataII.2.spike.present)))
# 88+33+91+25=237
	
# spike, relAbun
dataI.1.spike.relAbun = subset(otu.env1.spike.relAbun2, session == 'S1' & trap == 'M1' )
dataI.2.spike.relAbun = subset(otu.env1.spike.relAbun2, session == 'S1' & trap == 'M2' )
	
dataII.1.spike.relAbun = subset(otu.env1.spike.relAbun2, session == 'S2' & trap == 'M1' )
dataII.2.spike.relAbun = subset(otu.env1.spike.relAbun2, session == 'S2' & trap == 'M2' )
	
print(c(dim(dataI.1.spike.relAbun),dim(dataI.2.spike.relAbun), dim(dataII.1.spike.relAbun), dim(dataII.2.spike.relAbun)))
# 88+33+91+25=237
	

# .... if there's all zero OTUs ....
 dd = dataI.1.spike.present		# S1, M1, 0/1
# dd = dataI.2.spike.present		# S1, M2, 0/1
	
# dd = dataII.1.spike.present			# S2, M1, 0/1
# dd = dataII.2.spike.present		# S2, M2, 0/1
	
# dd = dataI.1.spike.relAbun		# S1, M1, abun
#dd = dataI.2.spike.relAbun		# S1, M2, abun
	
# dd = dataII.1.spike.relAbun		# S2, M1, abun
# dd = dataII.2.spike.relAbun		# S2, M2, abun
	
b = data.frame(otu=colnames(select(dd,contains('__'))), zero=apply(select(dd,contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
dim(b)
	
dd2 = dplyr::select(dd, -contains('__'),b$otu[b$zero==F])
dd2[1:5,34:45]
	
print(c(dim(dd), dim(dd2)))
	
 dataI.1.spike.present2 = dd2
# dataI.2.spike.present2 = dd2
	
# dataII.1.spike.present2 = dd2
# dataII.2.spike.present2 = dd2
	
# dataI.1.spike.relAbun2 = dd2
#dataI.2.spike.relAbun2 = dd2
	
# dataII.1.spike.relAbun2 = dd2
#dataII.2.spike.relAbun2 = dd2
	
rm(dd, dd2)
	
```

```{r NMDS lidar relAbun s1-m1}
# ............... NMDS with env.variable spike relAbun ...................
# . S1, M1 (88 sites, 850 otu) spike, relAbun .
dim(dataI.1.spike.relAbun2)
	
otu.table = as.data.frame(select(dataI.1.spike.relAbun2, contains('__')))
str(otu.table)
	
distI1.spike.relAbun = vegdist(wisconsin(otu.table))
str(distI1.spike.relAbun)
#88*87/2=3828
	
# 2D NMDS
set.seed(18756)
count.nmdsI1.spike.relAbun = metaMDS(distI1.spike.relAbun, distance='bray', try=30, trymax=2000, k=2, trace=T,plot=T, binary=F)
#... Procrustes: rmse 0.0007067015  max resid 0.005574035 
	
count.nmdsI1.spike.relAbun 
# Stress:     0.2256764 
	
plot(count.nmdsI1.spike.relAbun )
	
# 3D NMDS
set.seed(816)  # set the seed so that the result can be repeated
count.nmdsI1_3.spike.relAbun = metaMDS(distI1.spike.relAbun, distance='bray', try=30, trymax=2000, k=3, trace=T,plot=T)
#  ... Procrustes: rmse 0.0006529537  max resid 0.004731104
	
count.nmdsI1_3.spike.relAbun
# Stress:     0.1753416
	
plot(count.nmdsI1_3.spike.relAbun)
	
rm(otu.table)
	
# ..... fit env.data .....   
all.table = dataI.1.spike.relAbun2
nmds = count.nmdsI1.spike.relAbun 
names(all.table[,30:50])
	
# l_Cover_4m_16m_all & l_Cover_4m_16m would be similar anyway. eliminate l_Cover_4m_16m_all where there's 3 NAs

# with 2D NMDS
fitI1.spike.relAbun = envfit(nmds ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:2))
fitI1.spike.relAbun
	
plot(nmds, choices=c(1,2))
plot(fitI1.spike.relAbun, choices=c(1,2)) 
	
# with 3D NMDS
nmds3 = count.nmdsI1_3.spike.relAbun 
fitI1_3.spike.relAbun = envfit(nmds3 ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:3))
# yrs.disturb.min+canopy.ht+elevation+max.T+metre.road+old.growth.str+precipitation+min.T+metre.stream+hja
fitI1_3.spike.relAbun
	
a = data.frame(fitI1_3.spike.relAbun[[1]]$arrows)
range(scores(nmds3))
range(a)
	
d=scatterplot3d(range(a), range(a), range(a),type="n", xlab='nmds1', ylab='nmds2', zlab='nmds3') ;
d$points3d(scores(nmds3), pch=19)
d$points3d(a, pch=19, col='red')
	
for (i in 1:dim(a)[1]) {
	p2 <- d$xyz.convert(a[i,1],a[i,2],a[i,3])
	p3 <- d$xyz.convert(0,0,0)
	segments(p2$x,p2$y,p3$x,p3$y,lwd=2,col=2)
}
	
plot(nmds3, choices=c(2,3))
plot(fitI1_3.spike.relAbun, choices=c(2,3)) 
	
rm(nmds, nmds3, all.table)
	
```

```{r plot relAbun s1-m1}
# ..... combine NMDS to geographic map .....
# ... s1, M1 (88 sites) spike, relAbun ...
# use 2D NMDS!
all.table = dataI.1.spike.relAbun2
nmds = count.nmdsI1.spike.relAbun
gof = goodness(nmds)
fit.nmds = fitI1.spike.relAbun
	
pdf.name = 'nmds_geo_lidar_s1m1_relAbun.pdf'
plot.text = paste('relAbun, session 1, trap 1, 88 sites, 850 otu, stress ', round(nmds$stress,3),sep='')
	
stressplot(nmds)
range(gof)
	
fit.nmds
	
# . make a table for plotting (scores & goodness of fit of nmds & coordinates) .
nmds.geo.table = data.frame(UTM_E = all.table$UTM_E, UTM_N = all.table$UTM_N, nmds1 = nmds$points[,1], nmds2 = nmds$points[,2], good=gof, 
all.2.4m = all.table$l_Cover_2m_4m_all, 
max.2m = all.table$l_Cover_2m_max,
max.all.2m = all.table$l_Cover_2m_max_all)
str(nmds.geo.table)
	
c(range(nmds.geo.table$nmds1), range(nmds.geo.table$nmds2))
	
# . NMDS  .
#pdf(here('results','descriptive-graph','nmds_graph',paste(pdf.name)), width=15, height=15)
	
par(mfrow=c(2,2))
	
# . I. nmds with env.variables
plot(nmds, type='n', pch=19, choices=c(1,2), xlim=range(nmds.geo.table$nmds1)*1.1, ylim=range(nmds.geo.table$nmds2)*1.3, main=paste(plot.text))
points(nmds, display='sites', pch=19, cex=gof*50)
plot(fit.nmds, choices=c(1,2)) 
	

# . II. geo plots
plot.new()             
vps <- baseViewports()
	
g.1 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=all.2.4m, colour=nmds2)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_4m_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='disturb')
g.2 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=max.all.2m, colour=nmds2)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_max_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	
vp.BottomRight <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.5)
	
vp.BottomLeft <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.0)
	
vp.UpperRight<- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                          y=0.99, x=0.5)
	
print(g.1, vp=vp.UpperRight)
print(g.2, vp=vp.BottomLeft)
	
a = round(data.frame(fit.nmds[[1]]$arrows),3)
a$r2 = round(fit.nmds[[1]]$r,3)
a$'Pr(>r)' = fit.nmds[[1]]$pvals
	
grid.table(a, vp=vp.BottomRight)
	
rm(a)
	
#dev.off()
	
```

```{r NMDS lidar relAbun s2-m1}
# ................ NMDS with env.variable spike relAbun ..................
# . S2, M1 (91 sites, 715 otu) spike, relAbun .
otu.table = as.data.frame(dplyr::select(dataII.1.spike.relAbun2, contains('__')))
all.table = dataII.1.spike.relAbun2
dim(all.table)
	
dist = vegdist(wisconsin(otu.table))
str(dist)
# 91*45=4095
	
# 2D NMDS
set.seed(8156)
nmds2d = metaMDS(dist, distance='bray', try=30, trymax=6000, k=2, trace=T,plot=T)
#  Procrustes: rmse 0.001337755  max resid 0.009375236
	
nmds2d
# Stress:     0.2818142
	
# 3D NMDS
set.seed(8026)
nmds3d = metaMDS(dist, distance='bray', try=30, trymax=6000, k=3, trace=T,plot=T) # , previous.best=cmdscale(distI2.noS
#  . Procrustes: rmse 0.001106685  max resid 0.004912832 
	
nmds3d
# Stress:   0.2104009  
	
count.nmdsII1.spike.relAbun = nmds2d
count.nmdsII1_3.spike.relAbun = nmds3d
	

# ... fit env.var
# eliminate l_Cover_4m_16m_all because of the 3 NAs
# .. 2 dimensions
fit.2d = envfit(nmds2d ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:2))
	 
fit.2d
	
gof.2d = goodness(nmds2d)
range(gof.2d)
	
plot(nmds2d, type='n')
points(nmds2d, display='sites', cex=gof.2d*50)
plot(fit.2d)
	
# .. 3 dimensions
fit.3d = envfit(nmds3d ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:3))
fit.3d
	
gof.3d = goodness(nmds3d)
range(gof.3d)
	
plot(nmds3d, type='n', choices=c(1,3))
points(nmds3d, display='sites', cex=gof.3d*50)
plot(fit.3d, choices=c(1,3))
	
fitII1_3.spike.relAbun = fit.3d
	
rm(fit.2d, fit.3d, nmds2d, nmds3d, gof.2d, gof.3d)
	
```

```{r plot relAbun s2-m1}
# ... s2, m1 (91 sites, 715 otu) spike relAbun ...
# there's two graphs for using 3D NMDS

# I. plot 3-dimension NMDS plots
nmds = count.nmdsII1_3.spike.relAbun
gof = goodness(nmds)
fit.nmds = fitII1_3.spike.relAbun
	
pdf.text = 'nmds_lidar_s2m1_spike_relAbun.pdf'
plot.text = paste("kelpi 20200214, 3 mds, relAbun, session 2 (M1), stress ",round(nmds$stress,4), sep='')
	
#pdf(here('results','descriptive-graph','nmds_graph',paste(pdf.text)), width=11, height=11)
	
par(mfrow=c(2,2))
	
# 3 dim
plot(nmds, type='n', pch=19, choices=c(1,2), main=paste(plot.text))
points(nmds, display='sites', cex=gof*40, pch=19)
plot(fit.nmds, choices=c(1,2)) 
	
plot(nmds, type='n', pch=19, choices=c(2,3))
points(nmds, display='sites', cex=gof*40, pch=19)
plot(fit.nmds, choices=c(2,3)) 
	
plot(nmds, type='n', pch=19, choices=c(1,3))
points(nmds, display='sites', cex=gof*40, pch=19)
plot(fit.nmds, choices=c(1,3))
	
# .. fitenv table
plot.new()
vps <- baseViewports()
vp.BottomRight <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.5)
	
a = round(as.data.frame(fit.nmds[[1]]$arrows), 3)
a$r2 = round(fit.nmds[[1]]$r,3)
a$'Pr(>r)' = fit.nmds[[1]]$pval
	
grid.table(a, vp=vp.BottomRight)
	
rm(a)
#dev.off()
	

# II. combine NMDS to geographic map .....
all.table = dataII.1.spike.relAbun2
	
pdf.text = 'nmds_geo_lidar_s2m1_spike_relAbun.pdf'
	
nmds.geo.table = data.frame(
UTM_E = all.table$UTM_E, 
UTM_N = all.table$UTM_N, 
nmds1 = nmds$points[,1], 
nmds2 = nmds$points[,2], 
nmds3 = nmds$points[,3], 
good=gof, 
l2.4m = all.table$l_Cover_2m_4m, 
max.all.2m = all.table$l_Cover_2m_max_all,
p25.all = all.table$l_p25_all,
p95 = all.table$l_p95, 
rumple = all.table$l_rumple)
	
str(nmds.geo.table)
	
g.1 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=l2.4m, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_4m') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='disturb')
	
g.1.II = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=l2.4m, colour=nmds3)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_4m') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='disturb')
	
g.2 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=max.all.2m, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_max_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='hja')
	  
g.3 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=p25.all, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_p25_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	  
g.4 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=p95, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_p95') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	  
g.5 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=rumple, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_rumple') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	
#pdf(here('results','descriptive-graph','nmds_graph',paste(pdf.text)), width=18, height=12)
par(mfrow=c(2,3))
  
# geo plots
vp.ULeft <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=1, x=0.0)
	
vp.UMiddle <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=1, x=0.33)
	
vp.URight <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=1, x=0.67)
	
vp.BLeft <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.0)
	
vp.BMiddle<- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.33)
	
vp.BRight<- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.67)
	
print(g.1.II, vp=vp.ULeft)
print(g.1, vp=vp.UMiddle)
print(g.2, vp=vp.URight)
print(g.3, vp=vp.BLeft)
print(g.4, vp=vp.BMiddle)
print(g.5, vp=vp.BRight)
	
#dev.off()
	

```

```{r NMDS lidar 0/1 s1-m1}
# . S1, M1 (88 sites, 850 otu), 0/1 .
otu.table = as.data.frame(select(dataI.1.spike.present2, contains('__')))
str(otu.table)
all.table = dataI.1.spike.present2
	
distI1.spike.present = vegdist(wisconsin(otu.table))
str(distI1.spike.present)
#88*87/2=3828
	
# 2D NMDS
set.seed(87516)
nmds2d = metaMDS(distI1.spike.present, distance='bray', try=30, trymax=2000, k=2, trace=T,plot=T, binary=F)
#... Procrustes: rmse 0.0006187125  max resid 0.005188922
	  
nmds2d
# Stress:     0.2256677
	  
# 3D NMDS
set.seed(18756)  # set the seed so that the result can be repeated
nmds3d = metaMDS(distI1.spike.present, distance='bray', try=30, trymax=2000, k=3, trace=T,plot=T)
#  ... Procrustes: rmse 0.001204459  max resid 0.005170151 
	
nmds3d
# Stress:     0.1753449
	  
count.nmdsI1.spike.present = nmds2d
count.nmdsI1_3.spike.present = nmds3d
	
# ..... fit env.data .....   
names(all.table[,30:50])
	
# fitI1.spike.present = envfit(count.nmdsI1.spike.present ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_Cover_4m_16m_all + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=dataI.1.spike.present2, na.rm=T, choices=c(1:2))
# fitI1.spike.present
	
# l_Cover_4m_16m_all & l_Cover_4m_16m would be similar anyway. eliminate l_Cover_4m_16m_all where there's 3 NAs
fitI1.spike.present = envfit(nmds2d ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:2)) 
fitI1.spike.present
	
# fitI1_3.spike.present = envfit(count.nmdsI1_3.spike.present~l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_Cover_4m_16m_all + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=dataI.1.spike.present2, na.rm=T, choices=c(1:3))
# yrs.disturb.min+canopy.ht+elevation+max.T+metre.road+old.growth.str+precipitation+min.T+metre.stream+hja
# fitI1_3.spike.present
	
fitI1_3.spike.present = envfit(nmds3d ~l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:3))
fitI1_3.spike.present
	
plot(nmds2d, choices=c(1,2))
plot(fitI1.spike.present, choices=c(1,2)) 
	
a = data.frame(fitI1_3.spike.present[[1]]$arrows)
range(scores(nmds3d))
range(a)
d=scatterplot3d(range(a), range(a), range(a),type="n") ;
d$points3d(scores(nmds3d), pch=19)
d$points3d(a, pch=19, col='red')
	
p2 <- d$xyz.convert(a[2,1],a[2,2],a[2,3])
p3 <- d$xyz.convert(0,0,0)
segments(p2$x,p2$y,p3$x,p3$y,lwd=2,col=2)
	
rm(nmds2d, nmds3d)
	
  
```

```{r plot 0/1 s1-m1}
# ..... combine NMDS to geographic map .....
# ... s1, M1 (88 sites), 0/1 ...

# use 2D NMDS
all.table = dataI.1.spike.present2
nmds = count.nmdsI1.spike.present
fit.nmds = fitI1.spike.present
gof = goodness(nmds)
	
stressplot(nmds)
	
range(gof)
	
# make a table for plotting (scores & goodness of fit of nmds & coordinates) 
nmds.geo.table = data.frame(UTM_E = all.table$UTM_E, UTM_N = all.table$UTM_N, nmds1 = nmds$points[,1], nmds2 = nmds$points[,2], good=gof, 
all.2.4m = all.table$l_Cover_2m_4m_all, 
max.2m = all.table$l_Cover_2m_max,
max.all.2m = all.table$l_Cover_2m_max_all,
l4.16m = all.table$l_Cover_4m_16m,
p95 = all.table$l_p95, rumple = all.table$l_rumple)
str(nmds.geo.table)
	
c(range(nmds.geo.table$nmds1), range(nmds.geo.table$nmds2))
	
# . NMDS  .
plot.text = '0/1, session 1, trap 1, 88 sites, 850 otu'
	
#pdf(here('results','descriptive-graph','nmds_graph','nmds_geo_lidar_s1m1_present.pdf'), width=15, height=15)
	
par(mfrow=c(2,2))
	
# . I. nmds with env.variables
plot(nmds, type='n', pch=19, choices=c(1,2), xlim=c(min(nmds.geo.table$nmds1)*1.1,max(nmds.geo.table$nmds1)*1.1), ylim=c(min(nmds.geo.table$nmds2)*1.3, max(nmds.geo.table$nmds2)*1.3), main=paste(plot.text))
points(nmds, display='sites', pch=19, cex=gof*50)
plot(fit.nmds, choices=c(1,2)) 
	

# . II. geo plots
plot.new()             
vps <- baseViewports()
	
g.1 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=all.2.4m, colour=nmds2)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_4m_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='disturb')
	
g.2 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=max.all.2m, colour=nmds2)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_max_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	
vp.BottomRight <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.5)
	
vp.BottomLeft <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.0)
	
vp.UpperRight<- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                          y=0.99, x=0.5)
	
print(g.1, vp=vp.UpperRight)
print(g.2, vp=vp.BottomLeft)
	
a = round(data.frame(fit.nmds[[1]]$arrows),3)
a$r2 = round(fit.nmds[[1]]$r,3)
a$'Pr(>r)' = fit.nmds[[1]]$pvals
	
grid.table(a, vp=vp.BottomRight)
	
rm(a)
	
#dev.off()
	
rm(nmds, nmds.geo.table, fit.nmds, plot.text, gof)
	  
```

```{r NMDS lidar 0/1 s2-m1 }
# ................. NMDS with env.variable spike......................
# . S2, M1 (91 sites, 715 otu), 0/1 .
dim(dataII.1.spike.present2)
	
otu.table = as.data.frame(dplyr::select(dataII.1.spike.present2, contains('__')))
all.table = dataII.1.spike.present2
  	
distII1.spike.present = vegdist(wisconsin(otu.table))
str(distII1.spike.present)
# 91*45=4095
	
# 2D NMDS
set.seed(87156)
nmds2d = metaMDS(distII1.spike.present, distance='bray', try=30, trymax=6000, k=2, trace=T,plot=T)
#  Procrustes: rmse 0.001390123  max resid 0.009601155
	
nmds2d
# Stress:     0.2818141
	

# 3D NMDS
set.seed(18756)
nmds3d = metaMDS(distII1.spike.present, distance='bray', try=30, trymax=6000, k=3, trace=T,plot=T) # , previous.best=cmdscale(distI2.noS
#   Procrustes: rmse 0.002128049  max resid 0.01249923
	
nmds3d
# Stress:     0.2104043
	
stressplot(nmds3d)
  
count.nmdsII1.spike.present = nmds2d
count.nmdsII1_3.spike.present = nmds3d
	
# eliminate l_Cover_4m_16m_all because of the 3 NAs
fit3d = envfit(nmds3d ~ l_Cover_2m_4m + l_Cover_2m_4m_all + l_Cover_2m_max + l_Cover_2m_max_all + l_Cover_4m_16m + l_p25 + l_p25_all +l_p95 + l_p95_all + l_rumple, data=all.table, na.rm=T, choices=c(1:3))
	 
fit3d
  	
gof3d = goodness(nmds3d)
range(gof3d)
	
plot(nmds3d, type='n')
points(nmds3d, display='sites', cex=gof3d*50)
plot(fit3d)
  	
fitII1_3.spike.present = fit3d
	

# set.seed(333)  
# count.nmdsII1.spike.present = metaMDS(distII1.spike.present, distance='bray', try=30, trymax=2000, k=2, trace=T,plot=T)
# 2 dims cannot converge!

rm(nmds3d, nmds2d, fit3d, gof3d)
	
```

```{r plot 0/1 s2-m1}
# ... s2, m1 (91 sites, 715 otu) present ...
# 2 plots

# I. plot 3-dimension NMDS plots
all.table = dataII.1.spike.present2
nmds = count.nmdsII1_3.spike.present
fit.nmds = fitII1_3.spike.present
gof = goodness(nmds)
pdf.text = 'nmds_lidar_s2m1_present.pdf'
plot.text = paste("kelpi 20200214, 3 mds, 0/1, session 2 (M1), stress ",round(nmds$stress,4), sep='')
	
#pdf(here('results','descriptive-graph','nmds_graph', paste(pdf.text)), width=11, height=11)
	
par(mfrow=c(2,2))
	
# 3 dim
plot(nmds, type='n', pch=19, choices=c(1,2), main=paste(plot.text))
points(nmds, display='sites', cex=gof*40, pch=19)
plot(fit.nmds, choices=c(1,2)) 
	
plot(nmds, type='n', pch=19, choices=c(2,3))
points(nmds, display='sites', pch=19, cex=gof*40)
plot(fit.nmds, choices=c(2,3)) 
	
plot(nmds, type='n', pch=19, choices=c(1,3))
points(nmds, display='sites', pch=19, cex=gof*40)
plot(fit.nmds, choices=c(1,3)) 
	
# .. fitenv table
plot.new()
vps <- baseViewports()
vp.BottomRight <- viewport(height=unit(.5, "npc"), width=unit(0.5, "npc"), 
                           just=c("left","top"), 
                           y=0.5, x=0.5)
	
a = round(as.data.frame(fit.nmds[[1]]$arrows), 3)
a$r2 = round(fit.nmds[[1]]$r,3)
a$'Pr(>r)' = fit.nmds[[1]]$pval
	
grid.table(a, vp=vp.BottomRight)
	
rm(a)
#dev.off()
	
# II. combine NMDS to geographic map 
pdf.text = 'nmds_geo_lidar_s2m1_present.pdf'
    	
nmds.geo.table = data.frame(
UTM_E = all.table$UTM_E, 
UTM_N = all.table$UTM_N, 
nmds1 = nmds$points[,1], 
nmds2 = nmds$points[,2], 
nmds3 = nmds$points[,3], 
good=gof, 
l2.4m = all.table$l_Cover_2m_4m, 
max.all.2m = all.table$l_Cover_2m_max_all,
p25 = all.table$l_p25,
p95 = all.table$l_p95, 
rumple = all.table$l_rumple)
	
str(nmds.geo.table)
	  
g.1 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=l2.4m, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_4m') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) #+labs(size='disturb')
  	
g.2 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=max.all.2m, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_Cover_2m_max_all') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
  	
g.3 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=p25, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_p25') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
  	
g.4 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=p95, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_p95') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
  	
g.5 = ggplot(nmds.geo.table, aes(UTM_E, UTM_N, size=rumple, colour=nmds1)) + geom_point() + scale_colour_gradient(low='purple', high='orange') + ggtitle('l_rumple') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9)) 
	
#pdf(here('results','descriptive-graph','nmds_graph', paste(pdf.text)), width=18, height=12)
par(mfrow=c(2,3))
	
# . I. nmds with env.variables, plot 1:3
plot(nmds, type='n', pch=19, choices=c(1,3))
points(nmds, display='sites', pch=19)
plot(fit.nmds, choices=c(1,3)) 
	
# . II. geo plots
plot.new()
vps <- baseViewports()
	
vp.UMiddle <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=1, x=0.33)
	
vp.URight <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=1, x=0.67)
	
vp.BLeft <- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.0)
	
vp.BMiddle<- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.33)
	
vp.BRight<- viewport(height=unit(.5, "npc"), width=unit(0.33, "npc"), just=c("left","top"), y=0.5, x=0.67)
	
print(g.1, vp=vp.UMiddle)
print(g.2, vp=vp.URight)
print(g.3, vp=vp.BLeft)
print(g.4, vp=vp.BMiddle)
print(g.5, vp=vp.BRight)
	
#dev.off()
	
```

