# created: Sep 11, 2020
# last modified: Jan 20, 2021

```{r setup}
#setwd("/Volumes/Black_WD/HJA_analyses_Kelpie/sjSDM/R-git")
# setwd('/media/yuanheng/SD-64g2/Downloads/backup2/HJA_analyses_Kelpie/HJA_scripts/12_sjsdm_general_model_outputs')
	
lapply(c("ggplot2",'vegan', 'tidyverse','gridBase', 'grid', 'ggcorrplot','here', 'conflicted','reticulate','sjSDM','mgsub','vcd','RColorBrewer','glue',"gridExtra"), library, character.only=T)
	
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("importance", "sjSDM")
	
dr_here()
packageVersion('sjSDM')
#[1] ‘0.1.3.9000’
#[1] ‘0.1.0.9000’
	
source(here("source", "sjsdm_function.r"))
source(here("source", "sjsdm-analyse-functions.r"))
	
```


```{r set-names}
# ....... folder structure .......
# bioinfo structure
samtoolsfilter = "F2308" # F2308 filter only
samtoolsqual = "q48"
minimaprundate = 20200929
kelpierundate = 20200927
primer = "BF3BR2"
	
date.cross.validation = 20201119
envvar = 'gismslidar'
minocc = 5
abund = c('qp','pa') 
trap <- "M1"; period = "S1"
	
outputidxstatstabulatefolder = glue("outputs_minimap2_{minimaprundate}_{samtoolsfilter}_{samtoolsqual}_kelpie{kelpierundate}_{primer}_vsearch97")
outputpath = glue('../../Kelpie_maps/{outputidxstatstabulatefolder}')
	
cvfolder = glue("cv_outputs/results_{date.cross.validation}_{minocc}minocc_{envvar}_{abund}_loocv")
datafolder = glue("data_{date.cross.validation}_{minocc}minocc_{envvar}")
otudata = glue('otu.{abund}.csv')
	
sjsdmV = '0.1.3.9000' # package version
	
# names for graph
sjsdmVfolder = glue('sjsdm-{sjsdmV}')
	
```



```{r load files}
# load data
alldata = read.csv(here(outputpath, glue('sample_by_species_table_{samtoolsfilter}_minimap2_{minimaprundate}_kelpie{kelpierundate}_FSL_qp.csv')), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
dim(alldata)
names(alldata)[1:10]
	

```

```{r select-subsets, transform-data}
# ..... select trap, session .....
trap; period
	
alldata1 = subset(alldata, trap == 'M1' & period == 'S1')
dim(alldata1)
	
names(alldata1)[102:103]
	
a = alldata1 %>% select(contains('__'))
a = a[,which(specnumber(a, MARGIN=2)>=minocc)]
dim(a)
	
alldata1 = cbind(select(alldata1, -contains('__')), a)
dim(alldata1)
	
envnames = c("insideHJA", "elevation_m", "canopyHeight_m", "minT_annual", "precipitation_mm", "distToRoad_m", "distToStream_m", "YrsSinceDist", "B1_20180717", "B2_20180717", "B3_20180717", "B4_20180717", "B5_20180717", "B6_20180717", "B7_20180717", "B10_20180717", "B11_20180717", "NDVI_20180717", "EVI_20180717", "B_20180717", "G_20180717", "W_20180717", "l_Cover_2m_max", "l_Cover_2m_4m", "l_Cover_4m_16m", "l_p25", "l_p95", "l_rumple")
	
# quasiP
dataI.1.quasiP5 = select(alldata1, 'SiteName',starts_with('UTM'),envnames,contains('__'))
str(dataI.1.quasiP5[,1:35])
	
# 0/1
dataI.1.present5 = as.data.frame((select(dataI.1.quasiP5, contains('__'))>0)*1)
dataI.1.present5 = cbind(select(dataI.1.quasiP5, -contains('__')), dataI.1.present5)
str(dataI.1.present5[,1:35])
	

```


```{r make-graph}
#dataI.1.quasiP5, dataI.1.present5
names(dataI.1.quasiP5)[1:32]
names(select(dataI.1.quasiP5, contains('Ichneumon_memorator')))
	
qp = select(dataI.1.quasiP5, 1:31, "R5193.38__Insecta_Hymenoptera_Ichneumonidae_Ichneumon_memorator_BOLD_ACE4814_size.318")
names(qp)[32]='Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814'
	
pa = select(dataI.1.present5, 1:31, "R5193.38__Insecta_Hymenoptera_Ichneumonidae_Ichneumon_memorator_BOLD_ACE4814_size.318")
names(pa)[32]='Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814'
names(pa)
	
qp_318 = cbind(qp[,c(2,3,8,32)], shape1=as.numeric(qp$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814>0))
qp_R2766$shape1 = mgsub(qp_318$shape1, pattern=c(1,0), replacement=c(21,1))
qp1 = qp_318
qp1$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814[qp1$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814==0] =NA
qp2 = subset(qp_318, Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814==0)
	
pa_318 = cbind(pa, size1=as.numeric(mgsub(pa$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814, pattern=c(0,1), replacement=c(.6, 6.5))))
pa_318$shape1 = mgsub(pa_318$size1, pattern=c(.6,6.5), replacement=c(1,21))
pa1 = pa_318
pa1$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814[pa1$Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814==0] =NA
pa2 = subset(pa_318, Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814==0)
	
g.1.2 = ggplot(qp_318, aes(UTM_E, UTM_N, shape=shape1, colour=precipitation_mm)) + geom_point(data=qp1, shape=21, aes(fill=precipitation_mm, size=Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814)) + scale_fill_gradient2(low='black', mid='red',high='lavender', midpoint=max(pa1$precipitation_mm)/1.2) + scale_size(range = c(.4, 6.5)) + scale_colour_gradient2(low='black', mid='red',high='lavender', midpoint=max(pa1$precipitation_mm)/1.2) + labs(size = "OTU 'biomass'", shape='') + geom_point(data=qp2, shape=1, size=.6) + ggtitle('quasiP>0 (Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814)') + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', panel.background=element_rect(fill='gray98'), legend.title=element_text(size=8))+ scale_shape_manual(values=as.numeric(qp_318$shape1), labels='absent')
	
g.2 = ggplot(pa_318, aes(UTM_E, UTM_N, colour=precipitation_mm, size= factor(size1))) + geom_point(data=pa2, shape=1) + ggtitle('0/1 (Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814)') + geom_point(data=pa1) + scale_colour_gradient2(low='black', mid='red',high='lavender', midpoint=max(pa1$precipitation_mm)/1.2) + theme(plot.title= element_text(hjust=.5), text=element_text(family = "sans"), legend.position='bottom', legend.title=element_text(size=9), panel.background=element_rect(fill='gray98'))+ scale_size_manual(name="OTU", values=c(.6,6.5),labels=c('absent', 'present'))
	
g.hist3 = ggplot(qp, aes(x= precipitation_mm)) + geom_histogram()
g.hist4 = ggplot(qp, aes(x= Hymenoptera_Ichneumonidae_Ichneumon_memorator_ACE4814)) + geom_histogram()
	
# pdf(here(outputpath,'sjsdm_general_outputs','sjsdm-0.1.2.9000' ,'sjsdm-graph','compare', 'coord_wasp_preci_s1_m1_no4.pdf'), width=15, height=10)
	
grid.arrange(g.1.2, g.2, g.hist3, g.hist4, nrow=2, layout_matrix= rbind(c(1,2), c(3,4)), as.table=TRUE , heights=c(5,3))   # g.1, 
	
dev.off()
	

```


```{r load-sjsdm-models}
# . sjSDM-version = ‘0.1.2.9000’
# 0/1, quasiP >=5

model.pa = readRDS(here(outputpath,'sjsdm_general_outputs','sjsdm-0.1.2.9000','sjsdm-model-RDS', glue('s-jSDM_tuned.model_{period}_{trap}_{abund[2]}_min{minocc}_{envvar}_elevation_m-insideHJA.RDS')) )
result.pa = readRDS(here('results','sjsdm-model-RDS', 'sjsdm-0.1.0.9000','s-jSDM_result_s1_m1_present_no4_gis_20200909_0.1.0.RDS') )
	
summary(model.pa)
	
model.qp = readRDS(here('results','sjsdm-model-RDS', 'sjsdm-0.1.0.9000','s-jSDM_model_s1_m1_quasiP_no4_gis_20200908_0.1.0.RDS'))
result.qp = readRDS(here('results','sjsdm-model-RDS', 'sjsdm-0.1.0.9000','s-jSDM_result_s1_m1_quasiP_no4_gis_20200908_0.1.0.RDS') )
	
summary(model.qp)
	
# . plot variation partition
imp.pa =importance(model.pa)
imp.qp =importance(model.qp)
	
#pdf(here('results','sjsdm-graph','sjsdm-0.1.0.9000','sjsdm_s1_m1_gis_compare', 'vari.par_sjSDM_s1_m1_gis_no4_0.1.0.pdf'), width=8, height=5)
	
par(mfrow=c(1,2))
	
plot(imp.pa, cex=.8) #from s-jSDM package
title(paste('variation partition, 0/1, ',ncol(result$sigma), ' OTUs', sep=''))
	
plot(imp.qp, cex=.8) #from s-jSDM package
title(paste('variation partition, quasiP, ',ncol(result$sigma), ' OTUs', sep=''))
	
dev.off()
	
# differentiate order & family
imp.qp$names == imp.pa$names
impD = inner_join(data.frame(OTU=imp.qp$names, imp.qp$res$total), data.frame(OTU=imp.pa$names, imp.pa$res$total), by=c('OTU','OTU'), suffix = c(".qp", ".pa"))
str(impD)
	
impD$order = sapply(strsplit(sapply(str_split(impD$OTU, '__'), function(a) a[2]), '_'), function(a) a[2])
table(impD$order)
	
impD$family = sapply(strsplit(sapply(str_split(impD$OTU, '__'), function(a) a[2]), '_'), function(a) a[3])
sort(table(impD$family))
	
# 24 not defined
# Diptera (flies), Coleoptera (beetles, weevils), Lepidoptera (butterflies, moths), Hymenoptera (wasp,  bees, ants), Hemiptera (bugs)
# Muscidae (house flies), Geometridae (geometer moths), Cecidomyiidae (gall midges), Ichneumonidae (ichneumon wasps)
	
a = as.data.frame(impD %>% count(order))
a = subset(a, n>9)
impD = inner_join(impD, a, by=c('order'='order'))
str(impD)
	
impD$order = mgsub(impD$order, c('Diptera', 'Coleoptera', 'Lepidoptera', 'Hemiptera', 'Hymenoptera'), c('Fly', 'Beetle & Weevil', 'Butterfly & Moth', 'Bug', 'Wasp & Bee'))
impD$family = mgsub(impD$family, c('Muscidae', 'Geometridae', 'Cecidomyiidae', 'Ichneumonidae'), c('Fly', 'Moth', 'Gall midge', 'Ichneumon wasp'))
str(impD)
	
a = as.data.frame(impD %>% count(family))
a = subset(a, n>9)
impD2 = inner_join(impD, a, by=c('family'='family'))
impD2 = subset(impD2, family!='BOLD' & family != 'NA')
str(impD2)
	
table(impD2$order)
table(impD2$family)
	
#pdf(here('results','sjsdm-graph','sjsdm-0.1.0.9000', 'sjsdm_s1_m1_gis_compare', 'vari.family_sjSDM_s1_m1_gis_no4_0.1.0.pdf'), width=8, height=5)
	
titleText=paste('variation partition, ',nrow(data), ' OTUs', sep='')
legendText = 'Family (occurrence>9)'
source(here("R", "source", "sjsdm-analyse-functions.r"))
	
vp.plot(data=impD2, x1=2, x2=4, ind=9, textM=titleText, textL=legendText)
vp.plot(data=impD2, x1=5, x2=7, ind=9, textM=titleText, textL=legendText)
	
dev.off()
	
#pdf(here('results','sjsdm-graph','sjsdm-0.1.0.9000', 'sjsdm_s1_m1_gis_compare', 'vari.order_sjSDM_s1_m1_gis_no4_0.1.0.pdf'), width=8, height=5)
	
titleText=paste('variation partition, ',nrow(data), ' OTUs', sep='')
legendText = 'Order (occurrence>9)'
	
vp.plot(data=impD2, x1=2, x2=4, ind=8, textM=titleText, textL=legendText)
vp.plot(data=impD2, x1=5, x2=7, ind=8, textM=titleText, textL=legendText)
	
dev.off()
	
names(impD2)
	
aaa = subset(impD2, family=='Ichneumon wasp')
aaa
	
aaa[3,]
#R1468_10__Insecta_Hymenoptera_Ichneumonidae_NA_NA_BOLD_ACE8616_size.343

```


