---
title: "compare OTU tables"
author: "Douglas Yu"
date: "19/10/2020"
output: html_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(lubridate)
library(knitr)
library(beepr)
library(arsenal) # for summary(comparedf())
library(sjmisc) # for rotate_df()
library(pivottabler)
library(vegan)
library(fs)
library(furrr)
library(glue)
library(here)
library(scales)
library(janitor)
library(conflicted)
  conflict_prefer("mutate", "dplyr", quiet = TRUE)
  conflict_prefer("select", "dplyr", quiet = TRUE)
  conflict_prefer("summarise", "dplyr", quiet = TRUE)
  conflict_prefer("filter", "dplyr", quiet = TRUE)
  conflict_prefer("first", "dplyr", quiet = TRUE)
  conflict_prefer("here", "here", quiet = TRUE)
  conflict_prefer("separate", "tidyr", quiet = TRUE)
  conflict_prefer("unite", "tidyr", quiet = TRUE)
  conflict_prefer("trim", "sjmisc", quiet=TRUE)
  conflict_prefer("rescale", "scales", quiet=TRUE)
  conflict_prefer("rescale", "discard", quiet=TRUE)
# Real numbers, not scientific notation.
options(scipen = 999)
```


compare Yuanheng's output table with her original code to my table with the new code 1.1_idxstats_tabulate.Rmd (OTU numbers only)
The OTU numbers after FSL/qp correction are the same, but there is one more row in Doug's dataset:  HOBO-063_M1_S2
```{r}
otutab_yh <- read_csv(here("..", "..", "sjSDM", "R-git", "data", "kelpie_data", "formatted_data", "quasiP_lidar_mulspec_5_sample_by_species_table_F2308_minimap2_20200929_kelpie20200927.csv")) 

minocc <- 5 
otutab_dy <- idx_meta_genomecov_filtered_lysis_FSL_qp %>% 
  unite("site_trap_period", SiteName, trap, period) %>% 
  arrange() 
otutab_dy <- otutab_dy[ , specnumber(otutab_dy, MARGIN = 2) >= minocc] 

otutab_dyyh <- left_join(otutab_dy, otutab_yh, by = c("site_trap_period")) 
# lowest row is the sample that is not in Yuanheng's data table
otutab_diff <- otutab_dyyh %>% 
  select(site_trap_period, contains("Dolichovespula")) %>% 
  arrange(R10475.3__Insecta_Hymenoptera_Vespidae_Dolichovespula_adulterina_BOLD_AAI6347_size.972) 
  
otutab_dy <- otutab_dyyh %>% select(contains("__")) %>% select(contains("size="))
otutab_yh <- otutab_dyyh %>% select(contains("__")) %>% select(contains("size."))
colnames(otutab_yh) <- names(otutab_dy)
comparedf(otutab_dy, otutab_yh)
comparedfout <- summary(comparedf(otutab_dy, otutab_yh))
```

