---
title: "Hmsc Results"
author: "CD"
date: "10/12/2020"
output: html_document
---

<style type="text/css">
.main-container {
 max-width: 1800px;
 margin-left: auto;
 margin-right: auto;
}
</style>



```{r setup, include=FALSE}
wd <- here::here()
# wd <- "J:/UEA/gitRepos/HJA_analyses_Kelpie"
knitr::opts_chunk$set(echo =FALSE)
knitr::opts_knit$set(root.dir = file.path(wd, "Hmsc_CD"))

```

## HMSC Summary of results so far

```{r libraries, include = FALSE}
library(Hmsc)
library(kableExtra)
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r getResults}
# setwd(file.path(wd, "Hmsc_CD"))
## load results
# get results folders 
resF <- list.files("oregon_ada/results", pattern = "res\\d*_\\d{2}$", include.dirs = TRUE, full.names = T)
resF <- c(resF, list.files("oregon_ada/results", pattern = "RRR_test", include.dirs = TRUE, full.names = T))

## Loop through results folders, extract model definition, convergence results and evaluation

# rf <- resF[1]
modRes <- list()
meRes <- list()
```

```{r doX}
# loop through folders and extract model data and evalutation stats

for(rf in resF){
  
  # get model paths
  ms <- list.files(rf, pattern = "^models_.", full.names = TRUE, recursive = TRUE)
  
  # get model evaluation paths
  mf <- list.files(rf, pattern = "MF.*", full.names = TRUE, recursive = TRUE)
  
  # get highest thin and samples
  thin_vec <- sub(".*_thin_(\\d*)_.*", "\\1", ms)
  samples_vec <- sub(".*_samples_(\\d*)_.*", "\\1", ms)
  thin <- thin_vec[which.max(as.numeric(thin_vec))] # generally higher thin has highest samples.. for now.
  samples <- samples_vec[which.max(as.numeric(thin_vec))]
  rm(thin_vec, samples_vec)
  
  # load model 
  load(ms[grepl(paste0(".*_thin_", thin, "_samples_", samples, ".*\\.Rdata$"), ms)])

  # check for errors
  tryE <- !sapply(models, inherits, what = "try-error")
  
  # print models, predictors, no of Obs, random levels, etc
  #m <- models[[1]]; str(m)
  mod.specs <- lapply(models[tryE], function(m) {
    
    if(is.null(m$ranLevelsUsed)) rL <- NA else rL <- m$ranLevelsUsed
    if(is.null(m$XRRRFormula)) RRR_predictors = NA else RRR_predictors = as.character(m$XRRRFormula)[2]
    
    data.frame(
      predictors = as.character(m$XFormula)[2],
      obs = m$ny,
      nSp = m$ns,
      phylo = !is.null(m$phyloTree),
      rL = rL,
      RRR_predictors = RRR_predictors,
      ncRRR = m$ncRRR
      )
    
    })
  
  mod.df <- do.call(rbind, mod.specs)
  mod.df$name <- names(models)[tryE]
  rownames(mod.df) <- NULL  
  mod.df
  rm(mod.specs)
  
  ## Do convergence 
  load(list.files(rf, "beta.*\\.[rR]data", full.names = TRUE, recursive = TRUE))
  
  # Scale reduction factor - beta parameter, mean +/- sd
  all.psrf <- unlist(lapply(beta, function(x) sapply(x, function(y) sprintf("%.3f \U00B1 %.3f",mean(y), sd(y)))))
  mod.df$psrf <- all.psrf[match(paste(mod.df$name, thin, samples, sep = "_"), names(all.psrf))]
  rm(beta, all.psrf)
  
  ## do model evaluation
  load(mf[grepl(paste0(".*_thin_", thin, "_samples_", samples, ".*\\.Rdata$"), mf)]) # WAIC, MF, MFCV
  
  MFres <- t(do.call(data.frame,
                   lapply(MF[!is.na(MF)], function(x) sapply(x, function(y) sprintf("%.3f \U00B1 %.3f",mean(y), sd(y))))))
  MFCVres <- t(do.call(data.frame, 
                       lapply(MFCV[!is.na(MFCV)], function(x) sapply(x, function(y) sprintf("%.3f \U00B1 %.3f",mean(y), sd(y))))))
  
  colnames(MFres) <- paste0(colnames(MFres), "_expl")
  colnames(MFCVres) <- paste0(colnames(MFCVres), "_pred")
  
  mfs <- merge(MFres,MFCVres, by = "row.names")
  mod.df <- cbind(mod.df,  mfs[match(paste(mod.df$name, thin, samples, sep = "_"), mfs$Row.names),2:7])
  
  mod.df$thin <- as.numeric(thin)
  mod.df$samples <- as.numeric(samples)
  
  ## Collect all AUC data with species prevalence
  prevList <- lapply(models[tryE], function(m) {
    mev <- data.frame(prev = colSums(m$Y)/nrow(m$Y))
  })
  
  ind <- is.na(MF)
  
  ME_stats <- mapply(function(x,y,z,k) {
    
    mfdf <- do.call(data.frame, x)
    colnames(mfdf) <- paste0(colnames(mfdf), "_expl")
    
    mfcvdf <- do.call(data.frame, y)
    colnames(mfcvdf) <- paste0(colnames(mfcvdf), "_pred")
    
    
    cbind(rf = basename(rf),
          name = k, 
          mfdf,
          mfcvdf, 
          prev = z)}, MF[!ind], MFCV[!ind], prevList[!ind], names(prevList[!ind]), SIMPLIFY = FALSE)

  meRes[[which(rf == resF)]] <- do.call(rbind,ME_stats)
  
  rm(MF, MFCV, MFres, MFCVres, mfs, WAIC, thin, samples, ms, mf,modelnames)
  
  modRes[[which(rf == resF)]] <- mod.df
  
  }

all.df <- do.call(rbind, modRes)
all.me <- do.call(rbind, meRes)

rm(mod.df, modRes, resF, rf)

all.df <- all.df[order(all.df$AUC_pred, decreasing = TRUE),]

```



```{r printTable}
# format by groups
grps <- all.df %>%
  arrange(ncRRR==0, desc(AUC_pred))
grps <- setNames(table(grps$ncRRR == 0), c("RRR", "non RRR"))

all.df %>%
  arrange(ncRRR==0, desc(AUC_pred)) %>%
  knitr::kable(row.names = FALSE) %>%
  kableExtra::group_rows(index = grps) %>%
  kable_styling()

# rmarkdown::paged_table(all.df, options = list(rownames.print = FALSE))
# DT::datatable(all.df, rownames = FALSE)

```

```{r AUCplots}

## Relationship of AUC with prevalence

me.l <- pivot_longer(all.me, cols = colnames(all.me)[grepl("_expl|_pred", colnames(all.me))], 
                            names_to = c("metric", "type"), names_sep ="_")
# ends_with("_expl", "_pred")

res <- c("res20201202_01", "res20201204_01", "res20201209_01", "RRR_test2")

me.l %>%
  filter(!grepl("RRR|adj_evi|q", name) & rf %in% res & type == "pred") %>%
  ggplot(aes(x = prev, y = value))+
  geom_point()+
  facet_grid(rows = vars(metric), cols = vars(name), scales = "free_y")




```

