# Yuanheng
# create: Jul 23, 2020 2020
# last modified: Sep 28
# 1. change how to use spike-in
# 2. add lysis buffer info
# 3. subsets & 3 parts data for adagpu

```{r setup}
# setwd('/media/yuanheng/SD-64g2/Downloads/backup2/HJA_analyses_Kelpie/sjSDM/R-git')
	
lapply(c("ggplot2", "gridExtra",'vegan', 'labdsv', 'tidyverse', 'scatterplot3d', 'gridBase','conflicted', 'grid', 'ggcorrplot','here'), library, character.only=T)
	
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("importance", "sjSDM")
	
dr_here()
#packageVersion('sjSDM')
	
```

```{r load files}
# ('HJA_analyses_Kelpie/Kelpie_maps' folder) 
# version 20200917 (5 neighbour samples)
otu.env1.noS2 = read.csv(here('..','..','Kelpie_maps', 'outputs_minimap2_20200917_F2308_q48_kelpie20200916_BF3BR2_vsearch97','sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
dim(otu.env1.noS2) 
#[1]  237 1284
names(otu.env1.noS2)[1:27]
	
names(otu.env1.noS2)[1:26]=c('SiteName', 'UTM_E','UTM_N','old.growth.str', 'yrs.disturb','point.ID','poly.ID','AGENCY','unit.log', 'name.log','log.yr','yrs.log.2018','log.treat','yrs.disturb.level', 'elevation','canopy.ht','min.T','max.T', 'precipitation','metre.road', 'metre.stream', 'yrs.disturb.min','hja','trap','session','site_trap_period')
	
# spike input ratio from Mingjie
names(dplyr::select(otu.env1.noS2, contains('spike')))
	
spike_input = c('COI.SPIKE__Coleoptera_Mordellidae_0.4_NA_NA_NA_NA_NA'=1, 'COI.SPIKE__Coleoptera_Elateridae_0.8_NA_NA_NA_NA_NA'=9)
	
# lysis buffer info
lysis = read.csv(here('data','kelpie_data','lysis_buffer_volume_20200724.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
# 'lysis_buffer_volume_20200715.csv' has error
str(lysis)
	
```

```{r check with old format data}
# formatted data
otu.env1.present = read.csv(here('data','kelpie_data','formatted_data','present2_lidar_mulspec_sample_by_species_corr_table_F2308_minimap2_20200221_kelpie20200214.csv'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
dim(otu.env1.present)
str(otu.env1.present[,1:51])
	
otu.env.present = select(otu.env1.present, -'old.growth.str', -ends_with('.ID'), -contains('log.'),-contains('.log'), -'yrs.disturb.level', -'yrs.disturb', -contains('AGENCY'))
print(c(dim(otu.env.present), dim(otu.env1.present)))
	
# check calculated variables
par(mfrow=c(1,3))
hist(otu.env.ori22$l_p95, breaks=50)
hist(scale(otu.env.ori22$l_p95), breaks=50)
hist(otu.env.present$l_p95.scale, breaks=50)
	
sum(otu.env.present$l_p95.scale)
sum(scale(otu.env.ori22$l_p95))
	
summary(cut(round(scale(otu.env.ori22$l_p95), 6), breaks=seq(-1.7,2.5,length.out = 12)))
summary(cut(round(otu.env.present$l_p95.scale, 6), breaks=seq(-1.7,2.5,length.out = 12)))
	
```


```{r formate and combine all env-variables}
# .. delete not-needed ground data
otu.env.ori = select(otu.env1.noS2, -'old.growth.str', -ends_with('.ID'), -contains('log.'),-contains('.log'), -'yrs.disturb.level', -'yrs.disturb', -contains('AGENCY'))
#old.growth.str, yrs.disturb, point.ID, poly.ID, AGENCY, unit.log, name.log, log.yr, yrs.log.2018, log.treat, yrs.disturb.level
	
names(otu.env.ori)[1:16]
	
# ... load EO data 
mulspec.env = read.csv(here('..','..','HJA_scripts','10_eo_data','biodiversity_site_info_multispectral_2020-04-13.txt'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
str(mulspec.env)
	
lidar.env = read.csv(here('..','..','HJA_scripts','10_eo_data','biodiversity_site_info_lidar_20200518_cleaned.txt'), header=T, sep=',', stringsAsFactors = F, na.strings='NA')
str(lidar.env)
	
# ... add variables
# . lidar
sort(unique(lidar.env$SiteName)) == sort(unique(otu.env.ori$SiteName))
	
otu.env.ori2 = dplyr::left_join(otu.env.ori, select(lidar.env,-contains('UTM_'),a), by=c('SiteName', 'SiteName'), copy=F)
# check which samples are not matched
is.na(otu.env.ori2$l_Cover_2m_4m)
	
# ... multispectral
sort(unique(mulspec.env$SiteName)) == sort(unique(otu.env.ori2$SiteName))
	
# .. calculate mean and add
# calculate mean EVI, NVI, B, G, W values
mulspec.env$mean.NDVI = base::rowMeans(select(mulspec.env, starts_with('NDVI_'))/1000)
mulspec.env$mean.EVI = base::rowMeans(select(mulspec.env, starts_with('EVI_'))/1000)
	
# B -> Tasseled cap brightness; "G" -> Tasseled cap greenness; "W" -> Tasseled cap wetness
mulspec.env$mean.bright = base::rowMeans(select(mulspec.env, starts_with('B_')))
mulspec.env$mean.green = base::rowMeans(select(mulspec.env, starts_with('G_')))
mulspec.env$mean.wet = base::rowMeans(select(mulspec.env, starts_with('W_')))
	
# add mulspectual 
otu.env.ori22 = dplyr::left_join(otu.env.ori2, select(mulspec.env,'SiteName', starts_with('mean.')), by=c('SiteName', 'SiteName'), copy=F)
print(c(dim(otu.env.ori22), dim(otu.env.ori2)))
	
names(otu.env.ori22)[1:16]
names(otu.env.ori22)[1273:1290]
	
otu.env.ori2 = otu.env.ori22[,c(1:15, 1274:1289, 16:1273)]
	
names(otu.env.ori2)[1:32]
	
# ..... scale variables .....
a = select(otu.env.ori2, 4:11, starts_with('l_'), starts_with('mean.'))%>%rename(elevation.scale=1, canopy.ht.scale=2, min.T.scale=3, max.T.scale=4, precipitation.scale=5, metre.road.scale=6, metre.stream.scale=7, yrs.disturb.min.scale=8, l_Cover_2m_4m.scale=9, l_Cover_2m_4m_all.scale=10, l_Cover_2m_max.scale=11, l_Cover_2m_max_all.scale=12, l_Cover_4m_16m.scale=13, l_Cover_4m_16m_all.scale=14, l_p25.scale=15, l_p25_all.scale=16, l_p95.scale=17, l_p95_all.scale=18, l_rumple.scale=19, mean.NDVI.scale=20, mean.EVI.scale=21, mean.bright.scale=22, mean.green.scale=23, mean.wet.scale=24) %>% scale()
	
otu.env.ori22 = cbind(otu.env.ori2[,1:31], data.frame(a), otu.env.ori2[,32:dim(otu.env.ori2)[2]])
names(otu.env.ori22)[1:56]
	
# write.table(otu.env.ori22, here('data', 'kelpie_data', 'formatted_data', 'data_used_during_format', 'add_variables_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), sep = ",", row.names=F)
	
```

```{r explore lysis-info}
str(lysis)
head(lysis)
	
table(lysis$aliquot)
	
par(mfrow=c(1,2))
hist(lysis$added.lysis.buffer.ml.[lysis$aliquot==1.2])
hist(lysis$added.lysis.buffer.ml.[lysis$aliquot==0.6])
# add aliquot==1.2 when the DNA concentration is too low
	
table(lysis$lysis.batch)
	
```

```{r format lysis-info}
str(lysis)
sort(unique(lysis$sample)) == sort(unique(otu.env.ori22$site_trap_period))
	
names(otu.env.ori22)[1:56]
table(is.na(otu.env.ori22$site_trap_period))
	
# change '_' to '-'
a = str_replace(lysis$sample, "HOBO_", 'HOBO-')
a = str_replace(a, "SM_", 'SM-')
data.frame(a, lysis$sample)
lysis$sample = a
	
dim(otu.env.ori22)
#[1]  237 1313
	
otu.env1 = dplyr::left_join(otu.env.ori22, lysis, by=c('site_trap_period'='sample'))
dim(otu.env1)
#[1]  237 1318
	
table(is.na(otu.env1$'added.lysis.buffer.ml.'))
	
# check which samples are not matched
for (i in 1:length(otu.env1$site_trap_period)) {
	if (match(otu.env1$site_trap_period[i], lysis$sample, nomatch=0)==0) {
		print(otu.env1$site_trap_period[i])
	}
}
	
#[1] "HOBO-063_M1_S2"
#[1] "SM-06_M1_S1"
	
#otu.env1 = subset(otu.env1, site_trap_period!='NA')
otu.env1 = subset(otu.env1, site_trap_period!="HOBO-063_M1_S2" & site_trap_period!="SM-06_M1_S1")
	
otu.env1 = otu.env1[,c(1:55, 1314:1318, 56:1313)]
names(otu.env1)[1:61]
	
# .. calculate FSL
spike_reads = data.frame(
					select(otu.env1, 'site_trap_period'),
					select(otu.env1, names(spike_input)[1])/spike_input[1],
					select(otu.env1, names(spike_input)[2])/spike_input[2] )
	
spike = data.frame(select(spike_reads, 'site_trap_period'), spike.mean=rowMeans(spike_reads[,2:3]))
rowMeans(spike_reads[235,2:3])
dim(spike)
	
otu.env1$lysis.ratio = otu.env1$aliquot/otu.env1$'added.lysis.buffer.ml.'
hist(otu.env1$lysis.ratio)
	
dim(otu.env1)
	
otu.env1 = dplyr::left_join(otu.env1, spike, by=c('site_trap_period'='site_trap_period'))
otu.env1 = otu.env1[,c(1:60, 1319:1320, 61:1318)]
str(otu.env1[,1:63])
	
# 1320-62-2(spike) = 1256
#FSL[i,j] = log(otu.env1$mapped_reads/(lysis*spike))
FSL = select(otu.env1, 'site_trap_period', 'lysis.ratio','spike.mean', starts_with('R'))
dim(FSL)
	
a = FSL[,-c(1:3)]/(FSL$lysis.ratio*FSL$spike.mean)
dim(a)
	
a[1,5] == FSL[1,8]/(FSL$lysis.ratio[1]*FSL$spike.mean[1])
a[11,50] == FSL[11,53]/(FSL$lysis.ratio[11]*FSL$spike.mean[11])
	
FSL = cbind(FSL[,1:3],a)
sum(as.matrix(FSL[,4:1259]) )
str(FSL[,1:5])
	
par(mfrow=c(1,2))
hist(as.vector(as.matrix(FSL[,4:1259])),breaks=100)
hist(as.vector(as.matrix(log(FSL[,4:1259]))),breaks=100)
# not necessary to log now as sjSDM is a probit model
	
# ... combine with envir factors
names(otu.env1)[1:63]
print(c(dim(otu.env1), dim(FSL)))
otu.env1$site_trap_period == FSL$site_trap_period
	
fsl.env = dplyr::left_join(data.frame(otu.env1[,1:62]), data.frame(FSL[,c(1,4:1259)]), by=c('site_trap_period'='site_trap_period'))
dim(fsl.env)
fsl.env$site_trap_period == otu.env1$site_trap_period
	
# write.table(fsl.env, here('data','kelpie_data', 'formatted_data', 'data_used_during_format', 'FSL_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
	
```

```{r further format}
fsl.env1 = read.table(here('data','kelpie_data','formatted_data','data_used_during_format','FSL_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), sep = ",", header=T)
str(fsl.env1[,1:63])
	
# make a dataset with FSL >=5
str(select(fsl.env1, contains('spike')) )
data = fsl.env1
dim(as.data.frame(select(data, -contains('__'))))
	
dimotu=63
	
a = data.frame( index=dimotu:dim(data)[2], sel=specnumber(as.data.frame(select(data, contains('__'))), MARGIN=2) >4)
str(a)
table(a$sel)
	
fsl.env11 = select(data, 1:(dimotu-1), a$index[a$sel==T])
dim(fsl.env11)
names(fsl.env11)[1:63]
	
rm(data,a,dimotu)
	
dim(fsl.env11)
	
fsl.env11 = select(fsl.env11, -'l_Cover_4m_16m_all.scale',-"l_Cover_4m_16m_all")
	

# calculate quasi-probability
fsl.env1 = data.frame(sapply(select(fsl.env11, contains('__')), function(x) scales::rescale(log(x+0.001))))
dim(fsl.env1)
names(fsl.env11)[1:61]
	
fsl.env13 = cbind(fsl.env11[,1:60], fsl.env1)
	
# present dataset
a = as.data.frame(ifelse(select(fsl.env13, contains('__'))>0, 1, 0))
otu.env.present3 = cbind(select(fsl.env13, -contains('__')), a)
dim(otu.env.present3)
names(otu.env.present3)[1:61]
	
rm(a)
	
dim(fsl.env13)
dim(otu.env.present3)
	
# write.table(fsl.env13, here('data','kelpie_data','formatted_data','quasiP_lidar_mulspec_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
# write.table(otu.env.present3, here('data','kelpie_data','formatted_data','incidence_lidar_mulspec_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
	
```

```{r subsets}
# load data 
quasiP.env1 = read.table(here('data','kelpie_data','formatted_data','quasiP_lidar_mulspec_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), header=T, sep=',')
otu.env1.present = read.table(here('data','kelpie_data','formatted_data','incidence_lidar_mulspec_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), header=T, sep=',')
	
table(as.matrix(quasiP.env1) == as.matrix(fsl.env13))
table(as.matrix(otu.env1.present) == as.matrix(otu.env.present3))
	
dim(otu.env1.present)
dim(quasiP.env1)
	
# ......................... subsets of data ..................................
dataI.1.present = subset(otu.env1.present, session == 'S1' & trap == 'M1' )
dim(dataI.1.present)
	
#dataII.1.present = subset(otu.env1.present, session == 'S2' & trap == 'M1' )
	
dataI.1.quasiP = subset(quasiP.env1, session == 'S1' & trap == 'M1' )
dim(dataI.1.quasiP )
	
#dataII.1.quasiP = subset(quasiP.env1, session == 'S2' & trap == 'M1' )
	
print(c(dim(dataI.1.quasiP), dim(dataI.1.present)))
	
#print(c(dim(dataII.1.quasiP), dim(dataII.1.present)))
	
# .... if there's all zero OTUs ....
# .... S1
b = data.frame(otu=colnames(select(dataI.1.quasiP, contains('__'))), zero=apply(select(dataI.1.quasiP, contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
table(b$zero)
	
dataI.1.quasiP.5 = dplyr::select(dataI.1.quasiP, -contains('__'),b$otu[b$zero==F])
dim(dataI.1.quasiP.5)
dataI.1.quasiP.5[1:5,53:60]
	
b = data.frame(otu=colnames(select(dataI.1.present,contains('__'))), zero=apply(select(dataI.1.present,contains('__')),2,sum)==0)
b$otu=as.character(b$otu)
dim(b)
table(b$zero)
	
dataI.1.present.5 = dplyr::select(dataI.1.present, -contains('__'),b$otu[b$zero==F])
dim(dataI.1.present.5)
dataI.1.present.5[1:5,14:55]
	
print(c(dim(dataI.1.quasiP.5), dim(dataI.1.present.5)))
	
# check incidence >4
data = dataI.1.quasiP.5
dim(as.data.frame(select(data, -contains('__'))))
	
dimotu=61
	
a = data.frame(index=dimotu:dim(data)[2], sel=specnumber(as.data.frame(select(data, contains('__'))), MARGIN=2) >4)
str(a)
table(a$sel)
	
dataI.1.quasiP.5 = select(data, 1:(dimotu-1), a$index[a$sel==T])
dim(fsl.env13)
names(fsl.env13)[1:58]
	
rm(data,a,dimotu)
	
# separate Spatial, OTU, Env for Doug ...................
# quasi
quasiP_s1m1_S5 = select(dataI.1.quasiP.5, "SiteName","UTM_E","UTM_N","trap", "session","site_trap_period")
str(quasiP_s1m1_S5)
	
quasiP_s1m1_Y5 = select(dataI.1.quasiP.5, contains('__'))
str(quasiP_s1m1_Y5[,1:5])
dim(quasiP_s1m1_Y5)
	
quasiP_s1m1_X5 = select(dataI.1.quasiP.5, ends_with('.scale'))#"site_trap_period",
names(quasiP_s1m1_X5)
	
# write.table(quasiP_s1m1_X5, here('data', 'kelpie_data', 'for_adagpu', 's1m1_20200916_kelpie20200917', 'quasiP_s1m1_env_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
# write.table(quasiP_s1m1_Y5, here('data','kelpie_data','for_adagpu','s1m1_20200916_kelpie20200917','quasiP_s1m1_otu_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
# write.table(quasiP_s1m1_S5, here('data','kelpie_data','for_adagpu','s1m1_20200916_kelpie20200917','quasiP_s1m1_spatial_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
	
#0/1
#dataI.1.present.5
present_s1m1_S5 = select(dataI.1.present.5, "SiteName","UTM_E","UTM_N","trap", "session","site_trap_period")
str(present_s1m1_S5)
	
present_s1m1_Y5 = select(dataI.1.present.5, contains('__'))
str(present_s1m1_Y5[,1:5])
dim(present_s1m1_Y5)
	
present_s1m1_X5 = select(dataI.1.present.5, ends_with('.scale'))#"site_trap_period",
names(present_s1m1_X5)
	
# write.table(present_s1m1_X5, here('data','kelpie_data','for_adagpu','s1m1_20200916_kelpie20200917','incidence_s1m1_env_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
# write.table(present_s1m1_Y5, here('data','kelpie_data','for_adagpu','s1m1_20200916_kelpie20200917','incidence_s1m1_otu_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
# write.table(present_s1m1_S5, here('data','kelpie_data','for_adagpu','s1m1_20200916_kelpie20200917','incidence_s1m1_spatial_5_sample_by_species_table_F2308_minimap2_20200916_kelpie20200917.csv'), row.names=F, sep=',')
	

```
