---
title: "dataprep"
author: "Douglas Yu"
date: "30/08/2020"
output: html_document
---

```{r setup, eval=TRUE, include=TRUE}
# copy the following into each script   
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)

# script-specific libraries
suppressPackageStartupMessages({
  library(corrplot)
  library(vegan)
})

# general-use packages
suppressPackageStartupMessages({
  library(here)
  library(fs)
  library(glue)
  library(tidyverse) # loads a bunch of packages (see below)
  library(readxl)
  library(cowplot)
  library(lubridate)
  library(patchwork)
  library(broom)
  library(ggeffects)
  library(viridis)
  library(arsenal) # for summary(comparedf())
  library(sjmisc) # for rotate_df()
  library(envDocument)
  library(inspectdf)
  library(conflicted)
})

conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("mutate", "dplyr", quiet = TRUE)
conflict_prefer("select", "dplyr", quiet = TRUE)
conflict_prefer("summarise", "dplyr", quiet = TRUE)
conflict_prefer("first", "dplyr", quiet = TRUE)
conflict_prefer("here", "here", quiet = TRUE)
conflict_prefer("separate", "tidyr", quiet = TRUE)
conflict_prefer("unite", "tidyr", quiet = TRUE)
conflict_prefer("intersect", "dplyr", quiet = TRUE)
conflict_prefer("setdiff", "dplyr", quiet = TRUE) # w/out this, R crashes
conflict_prefer("to_factor", "sjmisc", quiet = TRUE)
conflict_prefer("trim", "glue", quiet = TRUE)

# Provide real numbers, not scientific notation.
options(scipen = 999)
```


```{r working directory}
here() # should be: "/Users/Negorashi2011/Dropbox/Working_docs/Luo_Mingjie_Oregon/HJA_analyses_Kelpie/sjSDM/R-git"
```


```{r read data file}
samtoolsfilter <- "F2308" # F2308 filter only
samtoolsqual <- "q48"
minimaprundate <- 20200929
kelpierundate <- 20200927
primer <- "BF3BR2"
trap <- "M1"
period <- "S1"

(outputidxstatstabulatefolder <- glue("outputs_minimap2_{minimaprundate}_{samtoolsfilter}_{samtoolsqual}_kelpie{kelpierundate}_{primer}_vsearch97"))

(otuenvfilename <- glue("otuenv_{trap}{period}_minimap2_{minimaprundate}_kelpie{kelpierundate}.csv"))

otuenv <- read_csv(here("..", "..", "Kelpie_maps", 
                        outputidxstatstabulatefolder, 
                        otuenvfilename
                        )
                   )
```

```{r edit XY.csv}
# scale XY data
XY.csv <- otuenv %>% 
  select(UTM_E, UTM_N)
```

```{r edit otu.data}
# otu.data
# keep OTUs with >=5 incidences
minocc <- 5 # set to high number (e.g. 20) for testing
otu.qp.csv <- otuenv %>% select(contains("__"))
otu.qp.csv <- otu.qp.csv[ , specnumber(otu.qp.csv, MARGIN = 2) >= minocc] 

# convert to 0/1 data
otu.pa.csv <- otu.qp.csv
otu.pa.csv[otu.pa.csv > 0] <- 1
```

```{r edit scale.env1.csv}
# default is all environmental covariates: GIS + MS + Lidar

env.scale.csv <- otuenv %>% select(!contains("__")) %>% 
  select(-SiteName, -trap, -period, -UTM_E, -UTM_N, -clearcut) %>% 
  mutate(insideHJA = ifelse(insideHJA == "yes", 1, 0))

names(env.scale.csv)
#  [1] "insideHJA"          "oldGrowthIndex"     "elevation_m"        "canopyHeight_m"    
#  [5] "minT_annual"        "maxT_annual"        "precipitation_mm"   "distToRoad_m"      
#  [9] "distToStream_m"     "YrsSinceDist"       "mean.NDVI"          "mean.EVI"          
# [13] "mean.bright"        "mean.green"         "mean.wet"           "mean.NDVI.scale"   
# [17] "mean.EVI.scale"     "mean.green.scale"   "mean.bright.scale"  "mean.wet.scale"    
# [21] "l_Cover_2m_4m"      "l_Cover_2m_4m_all"  "l_Cover_2m_max"     "l_Cover_2m_max_all"
# [25] "l_Cover_4m_16m"     "l_p25"              "l_p25_all"          "l_p95"             
# [29] "l_p95_all"          "l_rumple"      
corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")

# GIS variables: gis
# env.scale.csv <- env.scale.csv %>%
#   select(insideHJA, oldGrowthIndex, elevation_m, canopyHeight_m, minT_annual, precipitation_mm, distToRoad_m, distToStream_m, YrsSinceDist)
# 
# corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")


# MS variables + elevation: ms
# env.scale.csv <- env.scale.csv %>%
#   select(elevation_m, mean.NDVI, mean.EVI, mean.bright, mean.green, mean.wet)
# 
# corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")

# # or
# # LiDAR variables + elevation.scale
# env.scale.csv <- env.scale.csv %>%
#   select(elevation_m, l_Cover_2m_4m, l_Cover_2m_max, l_Cover_4m_16m, l_p25, l_p95, l_rumple)
# 
# corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")

# # or
# # MS + LiDAR + elevation.scale: gisms
# env.scale.csv <- env.scale.csv %>%
#   select(elevation_m, mean.NDVI, mean.EVI, mean.bright, mean.green, mean.wet, l_Cover_2m_4m, l_Cover_2m_max, l_Cover_4m_16m, l_p25, l_p95, l_rumple)
# 
# corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")

# # or
# # GIS + MS + LiDAR:  gismslidar
# env.scale.csv <- env.scale.csv %>%
#   select(insideHJA, oldGrowthIndex, elevation_m, canopyHeight_m, minT_annual, precipitation_mm, distToRoad_m, distToStream_m, YrsSinceDist, mean.NDVI, mean.EVI, mean.bright, mean.green, mean.wet, l_Cover_2m_4m, l_Cover_2m_max, l_Cover_4m_16m, l_p25, l_p95, l_rumple)
# 
# corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")

# # or
# # GIS + MS + LiDAR minimal set: gismslidarmin
env.scale.csv <- env.scale.csv %>%
  select(insideHJA, oldGrowthIndex, elevation_m, canopyHeight_m, minT_annual, distToRoad_m, distToStream_m, YrsSinceDist, mean.NDVI, mean.green, l_Cover_2m_4m, l_Cover_2m_max, l_Cover_4m_16m, l_p25, l_p95, l_rumple)

corrplot(cor(env.scale.csv), method = "ellipse", type = "lower")
```


These files are used as input to the sjsdm_cv() and sjsdm() code
```{r save data files}
# set variables
prepdate <- 20201005 # run date
minocc <- 5 # minimum occupancy (incidence) per OTU
envvar <- "gismslidarmin" # gismslidarmin, gismslidar, gis, ms, lidar, mslidar
(datafolder <- glue("data_{prepdate}_{minocc}minocc_{envvar}"))

dir_create(here("data", "kelpie_data", "for_adagpu", datafolder))

write_csv(env.scale.csv, here("data", "kelpie_data", "for_adagpu", datafolder,  "scale.env.csv"))

write_csv(XY.csv, here("data", "kelpie_data", "for_adagpu", datafolder, "XY.csv"))

write_csv(otu.qp.csv, here("data", "kelpie_data", "for_adagpu", datafolder,  "otu.qp.csv"))

write_csv(otu.pa.csv, here("data", "kelpie_data", "for_adagpu", datafolder, "otu.pa.csv"))
```

Upload to ~/Hja_sjsdm/


<details><summary>Reproducibility receipt</summary>
```{r}
# datetime
Sys.time()

# repository
git2r::repository(here::here())

env_doc("table", git = FALSE)
```
